<pre>--- Summary ---
Tests passed: 16 out of 18

--- Details ---
Test #0: passed 
Test #1: passed 
Test #2: passed 
Test #3: passed 
Test #4: passed 
Test #5: passed 
Test #6: passed 
Test #7: passed 
Test #8: passed 
Test #9: passed 
Test #10: passed 
Test #11: passed 
Test #12: passed 
Test #13: passed 
Test #14: passed 
Test #15: passed 
Test #16: failed 
Description: InsaneLearner Test Case (group: InsaneLearner)
IncorrectOutput: Test failed on one or more output criteria.
  Inputs:
    data file: simple.csv
    permutation: [49 12  5  1 15 47 46  6 48 21 40 28 30 14 41 17 45 20 36  4 24 31 35 33  8
 44 19  0 32 27  7 16 26 29 25  2 13  9  3 38 42 39 43 10 22 34 37 18 23 11]
  Failures:
    Exception calling InsaneLearner: __init__() takes exactly 6 arguments (5 given)

Test #17: failed 
Description: Random Classname Test Case (group: RandomName)
IncorrectOutput: Test failed on one or more output criteria.
  Inputs:
    data file: simple.csv
    permutation: [49 12  5  1 15 47 46  6 48 21 40 28 30 14 41 17 45 20 36  4 24 31 35 33  8
 44 19  0 32 27  7 16 26 29 25  2 13  9  3 38 42 39 43 10 22 34 37 18 23 11]
  Failures:
    Unexpected number of calls to __init__, sum=21 (should be 20), max=1 (should be 1), min=1 (should be 1)

</pre>
